package com.example.carBay;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller	
@RequestMapping(path="/index")
public class MainController {
	
	
@Autowired // This means to get the bean called userRepository
// Which is auto-generated by Spring, we will use it to handle the data
private UtenteRepository utenteRepository;

@PostMapping(path="/registrazione") // Map ONLY POST Requests

//usare model attribute

public @ResponseBody String aggiungiNuovoUtente ( @RequestParam String nome,
		@RequestParam String cognome, @RequestParam String username, 
		@RequestParam String dataNascita, @RequestParam String codiceFiscale, @RequestParam String indirizzo, 
		@RequestParam String email, @RequestParam String telefono, @RequestParam String password) {
	
// @ResponseBody means the returned String is the response, not a view name
// @RequestParam means it is a parameter from the GET or POST request

Utente n = new Utente();
n.setNome(nome);
n.setCognome(cognome);
n.setUsername(username);
n.setDataNascita(dataNascita);
n.setCodiceFiscale(codiceFiscale);
n.setIndirizzo(indirizzo);
n.setEmail(email);
n.setTelefono(telefono);
n.setPassword(password);
utenteRepository.save(n);
return "Saved";
}

//@GetMapping(path="/all")
//public @ResponseBody Iterable<Utente> getAllUsers() {
//// This returns a JSON or XML with the users
//return utenteRepository.findAll();
//}

}
