package com.example.carBay.controller;

import com.example.carBay.services.UtenteServiceImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.ResponseBody;

import com.example.carBay.model.Utente;
import com.example.carBay.repository.UtenteRepository;


@Controller	
public class RegistrazioneController {
	
	
@Autowired // This means to get the bean called userRepository
// Which is auto-generated by Spring, we will use it to handle the data
private UtenteServiceImpl utenteServiceImpl;


@GetMapping("/registrazione")
public String mostraRegistrazione(Model model) {

   model.addAttribute("utente", new Utente()); 
   return "registrazione";
}



@PostMapping("/confermaRegistrazione")
public String salvaUtente(@ModelAttribute Utente utente) {
    System.out.println("name="+utente.getNome()); //use a logger if you have one available
    utente.setPassword(new BCryptPasswordEncoder().encode(utente.getPassword()));
    utenteServiceImpl.save(utente);
    return "confermaRegistrazione";
}

}
